WIP

diff --git a/.github/workflows/check-versions.yml b/.github/workflows/check-versions.yml
--- a/.github/workflows/check-versions.yml
+++ b/.github/workflows/check-versions.yml
@@ -35,11 +35,16 @@ jobs:
   checkparam:
     name: Validate parameter
     runs-on: ubuntu-latest
+    outputs:
+      havesamls: ${{ steps.checkparam.outputs.havesamls }}
     steps:
-      - run: |
-          ${{ startsWith(inputs.tomls, '[') && endsWith(inputs.tomls, ']') }} && exit 0
-          echo '::error::Parameter tomls must be a JSON-encoded array'
-          exit 1
+      - id: checkparam
+        run: |
+          if [[ "${{ startsWith(inputs.tomls, '[') && endsWith(inputs.tomls, ']') }}" != 'true' ]] ; then
+            echo '::error::Parameter tomls must be a JSON-encoded array'
+            exit 1
+          fi
+          echo "havesamls=${{ fromJson(inputs.tomls)[0] != '' }}" >> "$GITHUB_OUTPUT"
 
   semver:
     name: Validate SEMVER compliance
@@ -64,7 +69,7 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - id: readtoml
-        if: ${{ needs.semver.result == 'skipped' }}
+        if: ${{ needs.semver.result == 'skipped' && needs.checkparam.havesamls == 'true' }}
         uses: SebRollen/toml-action@v1.0.2
         with:
           file: "${{ fromJson(inputs.tomls)[0] }}"
