WIP

diff --git a/.github/workflows/ut3.yml b/.github/workflows/ut3.yml
--- a/.github/workflows/ut3.yml
+++ b/.github/workflows/ut3.yml
@@ -62,7 +62,8 @@ jobs:
           tomls: ${{ matrix.job.tomls }}
       - id: result
         if: always() && !cancelled() && ( steps.test.outcome != matrix.job.expected )
-        run: echo "testfailed=true" >> "$GITHUB_RESULT"
+        run: exit 1
+        #run: echo "testfailed=true" >> "$GITHUB_RESULT"
 
   main:
     needs: [test]
